const myprojects = [
    {
        img: "./assets/capas/capa-relogio.png",
        titulo: "Relógio Digital",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Relogio-Digital",
        linkSite: "https://carlosresendep.github.io/Relogio-Digital/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-devclub-coffe.png",
        titulo: "DevClub Coffe",
        tech: "HTML, CSS",
        linkFont: "https://github.com/carlosresendeP/Devclub-coffe",
        linkSite: "https://carlosresendep.github.io/Devclub-coffe/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-conversor-de-moedas.png",
        titulo: "Conversor de Moedas",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Conversor-de-Moedas",
        linkSite: "https://carlosresendep.github.io/Conversor-de-Moedas/",
        Progress: false,
    },
    /*{
        img: "./assets/capas/capa-site-Devcar.png",
        titulo: "Dev Car",
        tech: "HTML, CSS",
        linkFont: "https://github.com/carlosresendeP/projeto-loja-de-carro",
        linkSite: "https://carlosresendep.github.io/projeto-loja-de-carro/",
        Progress: true,
    },*/
    {
        img: "./assets/capas/Capa-site-previsão.png",
        titulo: "Previsão do Tempo",
        tech: "HTML, CSS, JAVASCRIPT, API",
        linkFont: "https://github.com/carlosresendeP/app-previsao-do-tempo",
        linkSite: "https://carlosresendep.github.io/app-previsao-do-tempo/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-calculadora.png",
        titulo: "Calculadora",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Calculadora",
        linkSite: "https://carlosresendep.github.io/Calculadora/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-slider.png",
        titulo: "Dev Slider",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Slider-Paradise",
        linkSite: "https://cityofworld.netlify.app/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-tesla.png",
        titulo: "Dev Club Tesla",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Devclub-tesla",
        linkSite: "https://carlosresendep.github.io/Devclub-tesla/",
        Progress: false,
    },

    {
        img: "./assets/capas/capa-projeto-justly.png",
        titulo: "Projeto Justly Advogados",
        tech: "HTML, CSS",
        linkFont: "https://github.com/carlosresendeP/Projeto-justly",
        linkSite: "https://carlosresendep.github.io/Projeto-justly/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa CodeStrategy.png",
        titulo: "Code Strategy",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Code-Strategy",
        linkSite: "https://carlosresendep.github.io/Code-Strategy/",
        Progress: true,
    },
    {
        img: "./assets/capas/capa-dev-burguer.png",
        titulo: "Burger Store",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Projeto-Menu-DevBurger",
        linkSite: "https://carlosresendep.github.io/Projeto-Menu-DevBurger/",
        Progress: false,
    },
    {
        img: "./assets/capas/capa-traduto-codepoint.png",
        titulo: "Tradutor",
        tech: "HTML, REACT, TAILWINDCSS, JAVASCRIPT, API",
        linkFont: "https://github.com/carlosresendeP/Tradutor-CodePoint",
        linkSite: "https://tradutor-code-point.vercel.app/",
        Progress: false,
    },
    {
        img: "./assets/capas/Capa-cad-usuarios.png",
        titulo: "Cadastros de Usuários",
        tech: "HTML, REACT, STYLED COMPONENTS, JAVASCRIPT, API, NODE JS, MONGO-DB",
        linkFont: "https://github.com/carlosresendeP/Cadastros-de-usuarios",
        linkSite: "https://cadastros-de-usuarios.vercel.app/",
        Progress: false,
    },

    {
        img: "./assets/capas/capa-golden.png",
        titulo: "Página de Vendas ",
        tech: "HTML, CSS, Javascript",
        linkFont: "https://github.com/carlosresendeP/pagina-de-vendas",
        linkSite: "https://carlosresendep.github.io/pagina-de-vendas/",
        Progress: true,
    },

    {
        img: "./assets/capas/capa-architectural.png",
        titulo: "Site para Arquitetura",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Architectural-Designer",
        linkSite: "https://carlosresendep.github.io/Architectural-Designer/",
        Progress: true,
    },

    {
        img: "./assets/capas/capa-astreus-academia.png",
        titulo: "Dev Academia",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Astraeus-Academia",
        linkSite: "https://carlosresendep.github.io/Astraeus-Academia/",
        Progress: false,
    },

    {
        img: "./assets/capas/capa-decora-e-conforto.png",
        titulo: "Decora & Conforto",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Decora-Conforto-Moveis-Decoracao",
        linkSite: "https://carlosresendep.github.io/Decora-Conforto-Moveis-Decoracao/",
        Progress: false,
    },

    {
        img: "./assets/capas/capa-dentista-landing-page.png",
        titulo: "Landing page para Dentista",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Site-para-dentista",
        linkSite: "https://carlosresendep.github.io/Site-para-dentista/",
        Progress: true,
    },

    {
        img: "./assets/capas/thumb-barberdev.png",
        titulo: "BarberDev",
        tech: "HTML, CSS, SASS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Projeto-Barber-shop",
        linkSite: "https://barberdev-ten.vercel.app/",
        Progress: false,
    },

    {
        img: "./assets/capas/capa-project-nexcent.png",
        titulo: "Projeto Nexcent",
        tech: "HTML, REACT, STYLED COMPONENTS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/project-Nexcent",
        linkSite: "https://project-nexcent-theta.vercel.app/",
        Progress: false,
    }

];