const myprojects = [
    {
        id: 1,
        img: "./assets/capas/capa-relogio.png",
        description: "projeto de um relógio digital",
        titulo: "Relógio Digital",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Relogio-Digital",
        linkSite: "https://carlosresendep.github.io/Relogio-Digital/",
        Progress: false,
    },
    {
        id: 2,
        img: "./assets/capas/capa-devclub-coffe.png",
        description: "projeto de um site de café fictício",
        titulo: "DevClub Coffe",
        tech: "HTML, CSS",
        linkFont: "https://github.com/carlosresendeP/Devclub-coffe",
        linkSite: "https://carlosresendep.github.io/Devclub-coffe/",
        Progress: false,
    },
    {
        id: 3,
        img: "./assets/capas/capa-conversor-de-moedas.png",
        description: "projeto de um conversor de moedas",
        titulo: "Conversor de Moedas",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Conversor-de-Moedas",
        linkSite: "https://carlosresendep.github.io/Conversor-de-Moedas/",
        Progress: false,
    },
    {
        id: 4,
        img: "./assets/capas/Capa-site-previsão.png",
        description: "Projeto de site previsão do tempo",
        titulo: "Previsão do Tempo",
        tech: "HTML, CSS, JAVASCRIPT, API",
        linkFont: "https://github.com/carlosresendeP/app-previsao-do-tempo",
        linkSite: "https://carlosresendep.github.io/app-previsao-do-tempo/",
        Progress: false,
    },
    /*{
        id: 5,
        img: "./assets/capas/capa-calculadora.png",
        description: "projeto de uma calculadora",
        titulo: "Calculadora",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Calculadora",
        linkSite: "https://carlosresendep.github.io/Calculadora/",
        Progress: false,
    },*/
    {
        id: 6,
        img: "./assets/capas/capa-slider.png",
        description: "projeto de um slider",
        titulo: "Dev Slider",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Slider-Paradise",
        linkSite: "https://cityofworld.netlify.app/",
        Progress: false,
    },
    {
        id: 7,
        img: "./assets/capas/capa-tesla.png",
        description: "projeto de um site da tesla",
        titulo: "Dev Club Tesla",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Devclub-tesla",
        linkSite: "https://carlosresendep.github.io/Devclub-tesla/",
        Progress: false,
    },
    {
        id: 8,
        img: "./assets/capas/capa-projeto-justly.png",
        description: "projeto de um site de advogados copia do justly",
        titulo: "Projeto Justly Advogados",
        tech: "HTML, CSS",
        linkFont: "https://github.com/carlosresendeP/Projeto-justly",
        linkSite: "https://carlosresendep.github.io/Projeto-justly/",
        Progress: false,
    },
    {
        id: 9,
        img: "./assets/capas/capa-CodeStrategy.png",
        description: "projeto de um site de estratégia de código",
        titulo: "Code Strategy",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Code-Strategy",
        linkSite: "https://carlosresendep.github.io/Code-Strategy/",
        Progress: true,
    },
    {
        id: 10,
        img: "./assets/capas/capa-dev-burguer.png",
        description: "projeto de um site siples de hamburgueria fictícia com o navbar animado",
        titulo: "Burger Store",
        tech: "HTML, CSS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/Projeto-Menu-DevBurger",
        linkSite: "https://carlosresendep.github.io/Projeto-Menu-DevBurger/",
        Progress: false,
    },
    {
        id: 11,
        img: "./assets/capas/capa-traduto-codepoint.png",
        description: "projeto de um tradutor de linguas totalmente funcional",
        titulo: "Tradutor",
        tech: "HTML, REACT, TAILWINDCSS, JAVASCRIPT, API",
        linkFont: "https://github.com/carlosresendeP/Tradutor-CodePoint",
        linkSite: "https://tradutor-code-point.vercel.app/",
        Progress: false,
    },
    {
        id: 12,
        img: "./assets/capas/Capa-cad-usuarios.png",
        description: "projeto de um cadastro de usuários com o objetivo de treinar o uso de API",
        titulo: "Cadastros de Usuários",
        tech: "HTML, REACT, STYLED COMPONENTS, JAVASCRIPT, API, NODE JS, MONGO-DB",
        linkFont: "https://github.com/carlosresendeP/Cadastros-de-usuarios",
        linkSite: "https://cadastros-de-usuarios.vercel.app/",
        Progress: false,
    },
    {
        id: 13,
        img: "./assets/capas/capa-golden.png",
        description: "projeto de um site de vendas aleatório",
        titulo: "Página de Vendas ",
        tech: "HTML, CSS, Javascript",
        linkFont: "https://github.com/carlosresendeP/pagina-de-vendas",
        linkSite: "https://carlosresendep.github.io/pagina-de-vendas/",
        Progress: true,
    },
    /*{
        id: 14,
        img: "./assets/capas/capa-architectural.png",
        description: "projeto de um site para arquitetura",
        titulo: "Site para Arquitetura",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Architectural-Designer",
        linkSite: "https://carlosresendep.github.io/Architectural-Designer/",
        Progress: true,
    },*/
    {
        id: 15,
        img: "./assets/capas/capa-astreus-academia.png",
        description: "projeto de um site para academia",
        titulo: "Dev Academia",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Astraeus-Academia",
        linkSite: "https://carlosresendep.github.io/Astraeus-Academia/",
        Progress: false,
    },
    {
        id: 16,
        img: "./assets/capas/capa-decora-e-conforto.png",
        description: "projeto de um site de moveis e decoração",
        titulo: "Decora & Conforto",
        tech: "HTML, CSS, JavaScript, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/Decora-Conforto-Moveis-Decoracao",
        linkSite: "https://carlosresendep.github.io/Decora-Conforto-Moveis-Decoracao/",
        Progress: false,
    },
    {
        id: 17,
        img: "./assets/capas/capa-dentista-landing-page.png",
        description: "projeto de uma landing page para dentista",
        titulo: "Landing page para Dentista",
        tech: "HTML, CSS, JavaScript",
        linkFont: "https://github.com/carlosresendeP/Site-para-dentista",
        linkSite: "https://carlosresendep.github.io/Site-para-dentista/",
        Progress: true,
    },
    {
        id: 18,
        img: "./assets/capas/thumb-barberdev.png",
        description: "projeto de um site para barbearia",
        titulo: "BarberDev",
        tech: "HTML, CSS, SASS, JavaScript, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/Projeto-Barber-shop",
        linkSite: "https://barberdev-ten.vercel.app/",
        Progress: false,
        highlight: true,
    },
    {
        id: 19,
        img: "./assets/capas/capa-project-nexcent.png",
        description: "projeto de um site para uma empresa fictícia, com o objetivo de treinar o react",
        titulo: "Projeto Nexcent",
        tech: "HTML, REACT, STYLED COMPONENTS, JAVASCRIPT",
        linkFont: "https://github.com/carlosresendeP/project-Nexcent",
        linkSite: "https://project-nexcent-theta.vercel.app/",
        Progress: false,
    },
    {
        id: 20,
        img: "./assets/capas/Thumb-RubiaWebsite.png",
        description: "Site para uma profissional de saúde mental,",
        titulo: "Website Neuropsicóloga",
        tech: "HTML, CSS, JAVASCRIPT, BOOTSTRAP, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/Projeto-landing-page-neuropsicologa",
        linkSite: "https://projeto-rubialand-website.vercel.app/",
        Progress: false,
        highlight: true,
    },
    {
        id: 21,
        img: "./assets/capas/Thumb-chatDev.png",
        description: "Projeto funcional de um chat com web socket Modo de usar: Abre varias abas com o mesmo link e comece a conversar",
        titulo: "Chat",
        tech: "HTML, CSS, JAVASCRIPT, NODE JS, WEB SOCKET, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/DevChat",
        linkSite: "https://chat-frontend-z4cu.onrender.com/",
        Progress: false,
    },

    {
        id: 22,
        img: "./assets/capas/Thumb-archVision.png",
        description: "Projeto de um site de Architetura e Design",
        titulo: "Arch Vision",
        tech: "HTML, CSS, JAVASCRIPT, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/Dev-ArchVision",
        linkSite: "https://carlosresendep.github.io/Dev-ArchVision/",
        Progress: false,
        highlight: true,
    },
    {
        id: 23,
        img: "./assets/capas/Thumb-pizzaria-italiana.png",
        description: "Website de uma pizzaria italiana, com foco em design e usabilidade.",
        titulo: "Pizza Italiana",
        tech: "HTML, Styled Components, Javascript, React, ApiRest",
        linkFont: "https://github.com/carlosresendeP/Pizzaria-Italiaba-landingPage",
        linkSite: "https://carlosresendep.github.io/Pizzaria-Italiaba-landingPage/",
        Progress: false,
        specificPage: false,

    },
    {
        id: 24,
        img: "./assets/capas/Thumb-devprice.png",
        description: " Projeto de um site de buscador de preços de produtos",
        titulo: "Dev Price",
        tech: "Html, CSS, Javascript, bootstrap, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/Dev-Price-guide",
        linkSite: "https://dev-price.vercel.app/",
        Progress: false,
    },

    {
        id: 25,
        img: "./assets/capas/Thumb-DevBurger.png",
        description: "Projeto completo de uma hamburgueria com sistema de pedidos e pagamentos, cadastro de produtos",
        titulo: "Dev Burger",
        tech: "React, Styled Components, Javascript, Node JS, Mongo DB, API, Docker,Prisma, PostgresSQL",
        //linkFont:"https://github.com/carlosresendeP/Pizzaria-Italiaba-landingPage",
        linkSite: "./pages/Devbuger-Project/index.html",
        Progress: false,
        specificPage: true,

    },
    {
        id: 26,
        img: "./assets/capas/thumb-prime-digital.png",
        description: " Projeto de um site de uma agência de tecnologia, com foco em design e usabilidade.",
        titulo: "Prime Digital Studio",
        tech: "Html, CSS, Javascript, bootstrap, Mobile Responsive",
        linkFont: "https://github.com/carlosresendeP/site-prime-digital",
        linkSite: "https://primedigital-studio.vercel.app/",
        Progress: false,
        highlight: true,
        isNew: true,
    },
    {
        id: 27,
        img: "./assets/capas/thumb-app-dieta.png",
        description: "Primeiro app que desenvolvi durante um curso, app de que gera dietas personalizadas, foi utilizdo a IA do Gemini para gerar as dietas.",
        titulo: "App Dieta AI",
        tech: "Html, tailwindcss, Typescript, React-Native,expo, ApiRestful, Gemini, Node JS, frontend, backend",
        linkFont: "https://github.com/carlosresendeP/dietaai-app",
        linkSite: "",
        Progress: false,
        highlight: false,
        isNew: true,
    },


    {
        id: 28,
        img: "./assets/capas/Thumb-DevReceita.png",
        description: "Site de chatbot focado em gerar receitas de forma rápida e fácil, utilizando a IA do ChatGPT.",
        titulo: "Dev Receita",
        tech: "Html, tailwindcss, Javascript, React,  ApiRestful, OpenAI, Node JS, frontend, backend",
        linkFont: "https://github.com/carlosresendeP/DevReceita",
        linkSite: "https://dev-receita.vercel.app/",
        Progress: false,
        highlight: false,
        isNew: true,
    },


];